; Auto-generated. Do not edit!


(cl:in-package Project-msg)


;//! \htmlinclude mouvementResult.msg.html

(cl:defclass <mouvementResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass mouvementResult (<mouvementResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <mouvementResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'mouvementResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name Project-msg:<mouvementResult> is deprecated: use Project-msg:mouvementResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <mouvementResult>) ostream)
  "Serializes a message object of type '<mouvementResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <mouvementResult>) istream)
  "Deserializes a message object of type '<mouvementResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<mouvementResult>)))
  "Returns string type for a message object of type '<mouvementResult>"
  "Project/mouvementResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'mouvementResult)))
  "Returns string type for a message object of type 'mouvementResult"
  "Project/mouvementResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<mouvementResult>)))
  "Returns md5sum for a message object of type '<mouvementResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'mouvementResult)))
  "Returns md5sum for a message object of type 'mouvementResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<mouvementResult>)))
  "Returns full string definition for message of type '<mouvementResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'mouvementResult)))
  "Returns full string definition for message of type 'mouvementResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <mouvementResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <mouvementResult>))
  "Converts a ROS message object to a list"
  (cl:list 'mouvementResult
))
