; Auto-generated. Do not edit!


(cl:in-package Project-msg)


;//! \htmlinclude mouvementGoal.msg.html

(cl:defclass <mouvementGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass mouvementGoal (<mouvementGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <mouvementGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'mouvementGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name Project-msg:<mouvementGoal> is deprecated: use Project-msg:mouvementGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <mouvementGoal>) ostream)
  "Serializes a message object of type '<mouvementGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <mouvementGoal>) istream)
  "Deserializes a message object of type '<mouvementGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<mouvementGoal>)))
  "Returns string type for a message object of type '<mouvementGoal>"
  "Project/mouvementGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'mouvementGoal)))
  "Returns string type for a message object of type 'mouvementGoal"
  "Project/mouvementGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<mouvementGoal>)))
  "Returns md5sum for a message object of type '<mouvementGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'mouvementGoal)))
  "Returns md5sum for a message object of type 'mouvementGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<mouvementGoal>)))
  "Returns full string definition for message of type '<mouvementGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'mouvementGoal)))
  "Returns full string definition for message of type 'mouvementGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <mouvementGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <mouvementGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'mouvementGoal
))
