(cl:defpackage scara_cpe_kinemaics-msg
  (:use )
  (:export
   "<MOUVEMENTACTION>"
   "MOUVEMENTACTION"
   "<MOUVEMENTACTIONFEEDBACK>"
   "MOUVEMENTACTIONFEEDBACK"
   "<MOUVEMENTACTIONGOAL>"
   "MOUVEMENTACTIONGOAL"
   "<MOUVEMENTACTIONRESULT>"
   "MOUVEMENTACTIONRESULT"
   "<MOUVEMENTFEEDBACK>"
   "MOUVEMENTFEEDBACK"
   "<MOUVEMENTGOAL>"
   "MOUVEMENTGOAL"
   "<MOUVEMENTRESULT>"
   "MOUVEMENTRESULT"
  ))

