// Generated by gencpp from file scara_cpe_kinemaics/GoToXY.msg
// DO NOT EDIT!


#ifndef SCARA_CPE_KINEMAICS_MESSAGE_GOTOXY_H
#define SCARA_CPE_KINEMAICS_MESSAGE_GOTOXY_H

#include <ros/service_traits.h>


#include <scara_cpe_kinemaics/GoToXYRequest.h>
#include <scara_cpe_kinemaics/GoToXYResponse.h>


namespace scara_cpe_kinemaics
{

struct GoToXY
{

typedef GoToXYRequest Request;
typedef GoToXYResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoToXY
} // namespace scara_cpe_kinemaics


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::scara_cpe_kinemaics::GoToXY > {
  static const char* value()
  {
    return "37872fb1b1aa19c26302f3aa18acdaf5";
  }

  static const char* value(const ::scara_cpe_kinemaics::GoToXY&) { return value(); }
};

template<>
struct DataType< ::scara_cpe_kinemaics::GoToXY > {
  static const char* value()
  {
    return "scara_cpe_kinemaics/GoToXY";
  }

  static const char* value(const ::scara_cpe_kinemaics::GoToXY&) { return value(); }
};


// service_traits::MD5Sum< ::scara_cpe_kinemaics::GoToXYRequest> should match 
// service_traits::MD5Sum< ::scara_cpe_kinemaics::GoToXY > 
template<>
struct MD5Sum< ::scara_cpe_kinemaics::GoToXYRequest>
{
  static const char* value()
  {
    return MD5Sum< ::scara_cpe_kinemaics::GoToXY >::value();
  }
  static const char* value(const ::scara_cpe_kinemaics::GoToXYRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_cpe_kinemaics::GoToXYRequest> should match 
// service_traits::DataType< ::scara_cpe_kinemaics::GoToXY > 
template<>
struct DataType< ::scara_cpe_kinemaics::GoToXYRequest>
{
  static const char* value()
  {
    return DataType< ::scara_cpe_kinemaics::GoToXY >::value();
  }
  static const char* value(const ::scara_cpe_kinemaics::GoToXYRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::scara_cpe_kinemaics::GoToXYResponse> should match 
// service_traits::MD5Sum< ::scara_cpe_kinemaics::GoToXY > 
template<>
struct MD5Sum< ::scara_cpe_kinemaics::GoToXYResponse>
{
  static const char* value()
  {
    return MD5Sum< ::scara_cpe_kinemaics::GoToXY >::value();
  }
  static const char* value(const ::scara_cpe_kinemaics::GoToXYResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_cpe_kinemaics::GoToXYResponse> should match 
// service_traits::DataType< ::scara_cpe_kinemaics::GoToXY > 
template<>
struct DataType< ::scara_cpe_kinemaics::GoToXYResponse>
{
  static const char* value()
  {
    return DataType< ::scara_cpe_kinemaics::GoToXY >::value();
  }
  static const char* value(const ::scara_cpe_kinemaics::GoToXYResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCARA_CPE_KINEMAICS_MESSAGE_GOTOXY_H
