// Generated by gencpp from file scara_cpe_kinemaics/GoToXYResponse.msg
// DO NOT EDIT!


#ifndef SCARA_CPE_KINEMAICS_MESSAGE_GOTOXYRESPONSE_H
#define SCARA_CPE_KINEMAICS_MESSAGE_GOTOXYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace scara_cpe_kinemaics
{
template <class ContainerAllocator>
struct GoToXYResponse_
{
  typedef GoToXYResponse_<ContainerAllocator> Type;

  GoToXYResponse_()
    : finished(false)  {
    }
  GoToXYResponse_(const ContainerAllocator& _alloc)
    : finished(false)  {
  (void)_alloc;
    }



   typedef uint8_t _finished_type;
  _finished_type finished;





  typedef boost::shared_ptr< ::scara_cpe_kinemaics::GoToXYResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scara_cpe_kinemaics::GoToXYResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GoToXYResponse_

typedef ::scara_cpe_kinemaics::GoToXYResponse_<std::allocator<void> > GoToXYResponse;

typedef boost::shared_ptr< ::scara_cpe_kinemaics::GoToXYResponse > GoToXYResponsePtr;
typedef boost::shared_ptr< ::scara_cpe_kinemaics::GoToXYResponse const> GoToXYResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scara_cpe_kinemaics::GoToXYResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scara_cpe_kinemaics::GoToXYResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace scara_cpe_kinemaics

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'scara_cpe_kinemaics': ['/home/tp/catkin_ws/devel/share/scara_cpe_kinemaics/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::scara_cpe_kinemaics::GoToXYResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scara_cpe_kinemaics::GoToXYResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scara_cpe_kinemaics::GoToXYResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scara_cpe_kinemaics::GoToXYResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scara_cpe_kinemaics::GoToXYResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scara_cpe_kinemaics::GoToXYResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scara_cpe_kinemaics::GoToXYResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2797c797e620a950ba704492d72873b";
  }

  static const char* value(const ::scara_cpe_kinemaics::GoToXYResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2797c797e620a95ULL;
  static const uint64_t static_value2 = 0x0ba704492d72873bULL;
};

template<class ContainerAllocator>
struct DataType< ::scara_cpe_kinemaics::GoToXYResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scara_cpe_kinemaics/GoToXYResponse";
  }

  static const char* value(const ::scara_cpe_kinemaics::GoToXYResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scara_cpe_kinemaics::GoToXYResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool finished\n\
";
  }

  static const char* value(const ::scara_cpe_kinemaics::GoToXYResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scara_cpe_kinemaics::GoToXYResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.finished);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoToXYResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scara_cpe_kinemaics::GoToXYResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scara_cpe_kinemaics::GoToXYResponse_<ContainerAllocator>& v)
  {
    s << indent << "finished: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.finished);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCARA_CPE_KINEMAICS_MESSAGE_GOTOXYRESPONSE_H
